name: upgrade-npm-packages

on:
  workflow_dispatch: {}

jobs:
  upgrade-npm-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: "latest"
      - run: "npm install"
      - uses: fardjad/my-actions/automatic-maintenance@main
        with:
          script-base-path: ".github/upgrade-npm-packages"
          github-token: ${{ secrets.GH_PAT }}
